name: Continuous Integration
on: [push] # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest # Sets the build environment a machine with the latest Ubuntu installed
    steps:
      - uses: actions/checkout@v2 # Adds a step to checkout the repository code

      - name: Build C#
        run: dotnet build

      - name: Install Web dependencies
        working-directory: ./DotnetTemplate.Web
        run: npm install

      - name: Build Web dependencies
        working-directory: ./DotnetTemplate.Web
        run: npm run build

      - name: Run C# tests
        run: dotnet test

      - name: Run Typescript tests
        working-directory: ./DotnetTemplate.Web
        run: npm t

      - name: Run Typescript lint check
        working-directory: ./DotnetTemplate.Web
        run: npm run lint
